name: Development

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: macos-12
    steps:
    - name: Checkout 
      timeout-minutes: 5
      uses: actions/checkout@v3

    - name: Switch to latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build
      run: swift build -v

    - name: Test
      run: swift test -v
