name: Development

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      env:
        DEVELOPER_DIR: /Applications/Xcode_13.2.1.app
      run: xcodebuild test -scheme TextToEmoji